{% set name = "dash-bio" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dash_bio-{{ version }}.tar.gz
  sha256: 6de28e412a37aef19429579f3285c27a5d4f21d8f387564d0698d63466259a36

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - dash >=1.6.1
    - dash-core-components
    - dash-html-components
    - dash-table
    - pandas
    - scipy
    - scikit-learn >=0.20.1
    - biopython >=1.77
    - colour
    - geoparse >=1.1.0
    - jsonschema
    - parmed
    - periodictable
    - requests
    - typing_extensions

test:
  imports:
    - dash_bio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/plotly/dash-bio
  summary: Dash components for bioinformatics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
